[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "flittery"
version = "1.0"
dependencies = ["js2py", "pyyaml"]

[project.scripts]
flit = "engine:main"
